server:
  port: 9092
spring:
  application:
    name: almacen-b
  datasource:
    url: jdbc:mariadb://localhost:3306/logistica_db
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cassandra:
    keyspace-name: logistica_keyspace
    contact-points: localhost
    port: 9042
    local-datacenter: datacenter1
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: false
    register-with-eureka: false
